function highlight(title, detail, timeNeeded) {
  return { title, detail, timeNeeded }
}

function dish(name, detail) {
  return { name, detail }
}

function nearby(name, detail, travelTime) {
  return { name, detail, travelTime }
}

function day(title, morning, afternoon, evening) {
  return { title, morning, afternoon, evening }
}

function pack(item, reason) {
  return { item, reason }
}

export const oceania = [
  {
    id: 'hobart',
    name: 'Hobart',
    country: 'Australia',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['food', 'hiking', 'culture'],
    stayDays: 4,
    blurb:
      'Harbor markets, museum days, and mountain trails sit close together, with longer drives available if you add a rental car.',
    tagline: 'A working harbor under a mountain, with Saturday stalls and a ferry to an art bunker',
    overview:
      'Hobart sits between the Derwent and kunanyi / Mount Wellington, compact enough that a market morning, a museum afternoon, and a summit walk can share one stay. January is midsummer here: long light, festival weeks, and swimming weather in the river, though a southerly can still drop the mountain into cloud. Winter (June to August) is the quiet, frosty opposite — useful for indoor days and empty trails, not beach plans. The city rewards a Saturday for Salamanca and a separate day for the museum ferry, then a car if you want cliffs and convict ruins beyond the suburbs.',
    visitorProfile:
      'Best for travelers who want food and walking in the same compact base, and who will add a rental car only when the peninsula or east-coast beaches become the point.',
    climate: 'oceanic',
    coordinates: { lat: -42.8826, lng: 147.3257 },
    airport: 'HBA — Hobart Airport',
    timezone: 'Australia/Hobart',
    language: 'English',
    currency: 'AUD',
    walkability: 4,
    crowdLevel: 2,
    altitudeMeters: 54,
    costs: [190, 340, 680],
    gettingThere:
      'Domestic flights from Melbourne and Sydney are the usual approach; the airport sits east of the city with a short taxi or SkyBus run to the waterfront. International arrivals typically connect in Melbourne.',
    gettingAround:
      'The waterfront, Battery Point, and Salamanca are walkable. Metro buses climb some hills. A rental car unlocks the Tasman Peninsula, Bruny, and Freycinet; parking is easier outside Saturday market hours.',
    highlights: [
      highlight('Salamanca Market on Saturday', 'Farm stalls, leatherwood honey, and buskers fill the sandstone warehouses. Go at opening if you want oysters before the cruise-ship pulse.', '3 hours'),
      highlight('MONA by river ferry', 'The museum is the destination; the ferry past zinc works and headlands is half the point. Book timed entry and leave room to get lost underground.', '5 hours'),
      highlight('kunanyi / Mount Wellington summit', 'Boardwalks, dolerite columns, and a view that can vanish in ten minutes. Start clear and carry a warm layer even in January.', '3 hours'),
      highlight('Battery Point lanes', 'Weatherboard cottages, Arthur Circus, and pubs that still feel like a port town. Best on a weekday morning before tour groups.', '90 minutes'),
      highlight('Constitution Dock at dusk', 'Fishing boats, cray pots, and chips on the wharf. The mountain holds the last light after the streets empty.', '1 hour'),
      highlight('Royal Tasmanian Botanical Gardens', 'A calm, planted hour between harbor and Government House. Useful when the mountain is in cloud.', '90 minutes'),
    ],
    food: [
      dish('Scallop pie', 'A Tasmanian bakery staple: peppery scallops in a thick gravy under pastry. Eat it warm, standing, not as a plated novelty.'),
      dish('Pacific oysters', 'Farmed on the east coast and sold at the market or dock. A squeeze of lemon is enough; skip the heavy dressings.'),
      dish('Wallaby', 'Lean, slightly sweet red meat on a few serious menus. Closer to the island than another imported steak.'),
      dish('Leatherwood honey', 'Dark, floral, and specific to western rainforest. Taste it on bread or as ice cream, not as a jar you never open.'),
      dish('Tamar Valley or Coal River pinot', 'Cool-climate reds that make more sense here than a heavy shiraz. Pair with local cheese at a cellar door or a waterfront bar.'),
    ],
    nearby: [
      nearby('Tasman Peninsula', 'Port Arthur, sea cliffs, and the blowhole circuit. The day that justifies a rental car if the weather holds.', '80 minutes by car'),
      nearby('Bruny Island', 'Neck lookout, oysters, and a ferry hop that feels farther than the map. Better as a full day than a rushed loop.', '90 minutes including ferry'),
      nearby('Freycinet and Wineglass Bay', 'Granite peaks and a white-sand hook. Start early; the last stretch is a walk, not a drive-up viewpoint.', '2.5 hours by car'),
      nearby('Mount Field', 'Russell Falls and tall swamp gum in an easy national-park day west of the city.', '80 minutes by car'),
    ],
    itinerary: [
      day('Harbor and sandstone', 'Walk Sullivans Cove and Battery Point without a shopping list.', 'Salamanca warehouses or the botanical gardens.', 'Constitution Dock for a simple seafood dinner.'),
      day('Museum day', 'MONA ferry at opening.', 'Stay underground long enough to skip the urge to rush.', 'Return on the later boat; quiet waterfront night.'),
      day('Mountain air', 'kunanyi summit or the Organ Pipes track while the sky is clear.', 'Long lunch back in town.', 'Early night if tomorrow is a peninsula drive.'),
      day('Cliffs or buffer', 'Tasman Peninsula or Bruny if you hired a car.', 'Short coastal walk and a bakery stop.', 'Flight-buffer evening in the city.'),
    ],
    packing: [
      pack('Warm layer and a shell', 'January can still throw a cold front over the mountain; winter needs a real jacket.'),
      pack('Saturday cash or a charged card', 'Market stalls move faster if you are ready to pay.'),
      pack('Broken-in walking shoes', 'Dolerite, warehouse cobbles, and dock planks punish new boots.'),
    ],
    tips: [
      'Build the stay around Saturday if you care about Salamanca; midweek Hobart is quieter and still worth it.',
      'Check the mountain webcam before you drive; cloud on the summit is normal, not a personal failure.',
      'The MONA ferry is more pleasant than the car park at peak hours.',
      'A four-day stay works without a car; the peninsula is the reason to add one.',
    ],
    warnings: [
      'Summit weather changes faster than the harbor forecast. Turn around if the cloud drops.',
      'Wildlife on dusk roads is a real hazard if you drive back from Freycinet or the peninsula.',
    ],
    bestMonths: ['December', 'January', 'February', 'March'],
    tags: ['harbor', 'market', 'mona', 'mountain', 'peninsula'],
  },
  {
    id: 'queenstown',
    name: 'Queenstown',
    country: 'New Zealand',
    region: 'Oceania',
    budget: 'luxury',
    activities: ['hiking', 'wildlife', 'food'],
    stayDays: 5,
    blurb:
      'Lake views and trailheads are the draw, with enough restaurants and rest days to recover between longer alpine walks.',
    tagline: 'A lake town under sawtooth peaks, built for trail days and a proper dinner after',
    overview:
      'Queenstown is a small grid on Lake Wakatipu with trailheads, a busy airport, and restaurants that exist so you can walk hard and then sit down. January is high summer in this range: long light, open alpine tracks, and lake swims, not the snow-season picture northern visitors still pack for. June to August flips the town into ski mode, with short days and icy footpaths. The luxury is not another bungy photograph; it is a rest day between a ridge walk and a Milford weather window, plus a table that serves Central Otago wine when your legs are done.',
    visitorProfile:
      'For travelers who will pay for a good bed and a flexible day, and who treat adventure sports as optional rather than the whole itinerary.',
    climate: 'alpine',
    coordinates: { lat: -45.0312, lng: 168.6626 },
    airport: 'ZQN — Queenstown Airport',
    timezone: 'Pacific/Auckland',
    language: 'English, te reo Māori',
    currency: 'NZD',
    walkability: 3,
    crowdLevel: 4,
    altitudeMeters: 310,
    costs: [240, 450, 920],
    gettingThere:
      'Direct domestic flights from Auckland, Wellington, and Christchurch land beside the lake. International connections often come through Auckland. The airport is a short taxi or airport-bus hop from town.',
    gettingAround:
      'The center is walkable; the gondola and water-taxi save some climbs. Hire a car for Glenorchy, Gibbston, and Wanaka. Coach tours handle Milford if you do not want the driving day.',
    highlights: [
      highlight('Ben Lomond or Queenstown Hill', 'A proper climb with a lake-and-Remarkables payoff. Start early in January; afternoon cloud builds on the peaks.', '4 hours'),
      highlight('Glenorchy road at the lake edge', 'Beech forest, braided river mouths, and a village that still feels like a road end. Stop more than you photograph from the car.', 'Half day'),
      highlight('Kea on a high saddle', 'Olive-green mountain parrots with a taste for rubber. Watch, do not feed, and pack snacks out of reach.', 'During a hike'),
      highlight('Gibbston valley cellar doors', 'Pinot noir in schist country after a walking day. One or two rooms beat a full tasting crawl.', '3 hours'),
      highlight('Lake Wakatipu at blue hour', 'The steamer whistle, cold water, and the Remarkables turning pink. Walk the beach path rather than another viewpoint drive.', '1 hour'),
      highlight('Arrowtown autumn or summer lanes', 'A gold-rush street that is worth it if you arrive before the coach park fills. Chinese village remnants sit just beyond the shops.', '2 hours'),
    ],
    food: [
      dish('Central Otago pinot noir', 'The regional signature. Drink it with lamb or a cheese board, not as a rushed tasting-room checklist.'),
      dish('High-country lamb', 'Local flocks, simple sides, and a meal that matches the landscape. Lunch after a hike beats a late heavy dinner.'),
      dish('Whitebait fritter', 'Seasonal, expensive, and worth it when the run is on. A squeeze of lemon, nothing else.'),
      dish('Cardrona or local alpine cheese', 'Washed-rind and alpine styles that travel well to a lakeside picnic.'),
      dish('Bluff oysters in season', 'Southern oysters that appear on menus in autumn and winter. Order them when you see them.'),
    ],
    nearby: [
      nearby('Glenorchy and Paradise', 'Trailheads toward Routeburn country and a quieter lake shore. A half day or an overnight if you want silence.', '45 minutes by car'),
      nearby('Milford Sound / Piopiotahi', 'A weather-dependent fiord day. Cloud and rain are part of the place, not a refund condition.', '4 hours by car each way'),
      nearby('Wānaka', 'A calmer lake town with its own hill walks. Easy as a day if you do not linger in every photo stop.', '75 minutes by car'),
      nearby('Arrowtown', 'Schist cottages and a river walk. Pair it with a Gibbston tasting on the way back.', '25 minutes by car'),
    ],
    itinerary: [
      day('Arrive and drop the bags', 'Short lake walk and a look at the skyline.', 'Easy Queenstown Hill if legs allow.', 'Early dinner; airport days run long.'),
      day('A real trail', 'Ben Lomond or a guided Routeburn day-section while the weather window is open.', 'Cafe recovery in town.', 'Quiet night, no late bar crawl.'),
      day('Rest and food', 'Sleep in. Gondola or a lakeside swim in summer.', 'Gibbston cellar door.', 'Proper dinner without rushing.'),
      day('Farther west or another ridge', 'Glenorchy road or a Milford tour if the forecast cooperates.', 'Short walk at the far end.', 'Late return; keep the next morning light.'),
      day('Buffer and fly', 'Arrowtown or a last lakeside coffee.', 'Pack and a swim if January is being kind.', 'Airport with slack for alpine wind delays.'),
    ],
    packing: [
      pack('Layered hiking kit and a hard shell', 'Alpine weather ignores the calendar. January sun still sits beside a cold wind on the ridge.'),
      pack('Insect repellent', 'Sandflies at lake edges and trailheads are not a myth.'),
      pack('Warm evening layer', 'Even after a hot trail day the lakefront drops fast after sunset.'),
    ],
    tips: [
      'Book the flexible activity, not the cheapest fixed slot; wind closes the airport and some tracks without apology.',
      'Five nights lets you take a rest day. Four nights tempts you to stack two big drives.',
      'Milford is a long day from here. Treat rain as the normal forecast.',
      'Wildlife means kea, paradise ducks, and lake birds — not a safari. Binoculars still help.',
    ],
    warnings: [
      'Underestimate alpine weather and you get hypothermic on a track that looked easy from town.',
      'Adventure-sport insurance exclusions are common. Read the policy before you book a jump or a canyon.',
    ],
    bestMonths: ['December', 'January', 'February', 'March'],
    tags: ['alpine', 'lake', 'trails', 'pinot', 'fiord'],
  },
  {
    id: 'melbourne',
    name: 'Melbourne',
    country: 'Australia',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['food', 'city', 'culture'],
    stayDays: 4,
    blurb:
      'Laneway coffee, gallery hours, and tram loops make a walkable city stay, with coast and vineyard days if you add a car or tour.',
    tagline: 'Trams, graffiti lanes, and a city that treats lunch as a serious appointment',
    overview:
      'Melbourne is a grid of laneways inside a wider sprawl of trams, parks, and sports grounds. January is summer: long evenings on the Yarra, beach weather at St Kilda, and the occasional 40-degree northerly that empties the streets at noon. Winter (June to August) is grey, football-season, and built for galleries and broth. The point is not a single monument. It is a coffee walk, a few hours at the NGV, and a neighborhood dinner far from the hotel strip. Four days is enough if you pick one outer day — ocean road, penguins, or the Yarra Valley — and refuse to do all three.',
    visitorProfile:
      'For travelers who plan days around meals and museums, and who accept that weather can flip twice before dinner.',
    climate: 'oceanic',
    coordinates: { lat: -37.8136, lng: 144.9631 },
    airport: 'MEL — Melbourne Airport (Tullamarine)',
    timezone: 'Australia/Melbourne',
    language: 'English',
    currency: 'AUD',
    walkability: 5,
    crowdLevel: 3,
    altitudeMeters: 31,
    costs: [200, 360, 760],
    gettingThere:
      'Tullamarine is the main international and domestic airport, with SkyBus and taxis to the CBD. Avalon handles some budget flights and needs a longer transfer. Interstate trains arrive at Southern Cross.',
    gettingAround:
      'The free City Circle tram and a myki card cover the inner grid. Walk the laneways. Trains and trams reach St Kilda, Fitzroy, and the river parks. Day tours or a rental handle the Great Ocean Road.',
    highlights: [
      highlight('Laneway coffee crawl', 'Espresso bars in former loading docks. Order at the window, stand in the lane, and do not treat it as a photo set.', '2 hours'),
      highlight('NGV International and Ian Potter Centre', 'A serious pair of collections split across the river. Pick one building per visit if you hate museum fatigue.', '3 hours'),
      highlight('Queen Victoria Market', 'Produce, delis, and a Saturday swarm. Go for breakfast ingredients or a simple roll, not a full souvenir circuit.', '2 hours'),
      highlight('Royal Botanic Gardens and the Tan', 'A planted bowl beside the Yarra. Walkers and rowers set the pace on a warm January evening.', '90 minutes'),
      highlight('Street art in Hosier and Rutledge Lanes', 'Murals that change. Look, then leave; the surrounding bars are optional.', '45 minutes'),
      highlight('Tram to a neighborhood dinner', 'Fitzroy, Carlton, or Richmond beat another CBD tasting menu. Ride past your stop once to read the street.', 'Evening'),
    ],
    food: [
      dish('A proper flat white', 'Melbourne’s daily ritual. One excellent cup in a lane is better than a flight of novelty syrups.'),
      dish('Yum cha in the CBD or the suburbs', 'Carts, pot tea, and a late morning that replaces brunch. Go with a group if you can.'),
      dish('Chicken parma', 'Pub schnitzel under ham and cheese. A local comfort plate, not a chef’s signature.'),
      dish('Melbourne dim sim', 'A larger, pork-and-cabbage dumpling from takeaway windows. Eat it with soy, not irony.'),
      dish('Yarra Valley wine at the source', 'Pinot and chardonnay an hour from town. One cellar door and a long lunch beat a six-stop bus.'),
    ],
    nearby: [
      nearby('Great Ocean Road', 'Stack and cliff country west of town. A long day or an overnight; do not treat it as a two-hour outing.', 'Full day by car'),
      nearby('Yarra Valley', 'Vineyards and cool-climate cellars. Easy as a tour if you want to drink.', '90 minutes by car'),
      nearby('Mornington Peninsula', 'Bay beaches, hot springs, and more wine. A calmer coast day than the ocean road.', '90 minutes by car'),
      nearby('Phillip Island', 'Summer penguin parade and a coastal boardwalk. Book the official viewing if you go for the birds.', '90 minutes by car'),
    ],
    itinerary: [
      day('Grid and lanes', 'Coffee, then a laneway wander without a shopping list.', 'NGV or the Ian Potter Centre.', 'Neighborhood dinner on a tram line.'),
      day('Markets and parks', 'Queen Victoria Market at opening.', 'Royal Botanic Gardens and a Yarra path.', 'St Kilda foreshore if January is warm.'),
      day('One outer day', 'Ocean road, Yarra Valley, or penguins — pick one.', 'Do not add a second long drive.', 'Simple city supper on return.'),
      day('Inner-north or buffer', 'Fitzroy bookshops and galleries.', 'A long lunch.', 'Airport-buffer evening in the CBD.'),
    ],
    packing: [
      pack('A light waterproof and a sun layer', 'Four seasons in a day is a cliché because it is true, including in January heat.'),
      pack('Comfortable city shoes', 'Laneway bluestone and tram stops add up.'),
      pack('Swimwear in summer', 'St Kilda and bay beaches are close enough to use.'),
    ],
    tips: [
      'Buy a myki and stop treating every trip as a taxi problem.',
      'Book NGV ticketed shows; the permanent rooms can wait if you are short on time.',
      'January heat is real. Shift walking to morning and late afternoon.',
      'One day trip is enough. The city is the reason to stay four nights.',
    ],
    warnings: [
      'UV is harsh even on cloudy summer days. Hats are not optional at midday.',
      'Tram tracks and wet bluestone are slick. Watch your step in winter rain.',
    ],
    bestMonths: ['March', 'April', 'October', 'November'],
    tags: ['laneways', 'coffee', 'galleries', 'trams', 'yarra'],
  },
  {
    id: 'sydney',
    name: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    budget: 'luxury',
    activities: ['city', 'beach', 'food'],
    stayDays: 4,
    blurb:
      'Harbor ferries, ocean pools, and a dense restaurant scene let you split days between the water and inner-city neighborhoods.',
    tagline: 'A harbor city that still runs on ferries, ocean baths, and a late table',
    overview:
      'Sydney is a set of bays and headlands stitched by ferries, with a CBD that is almost beside the water and beaches that are a bus or coastal walk away. January is high summer: humid, bright, and built for early ocean pools before the nor’easter chops the afternoon. A southerly buster can drop the temperature in an hour. June to August is the cool, clearer opposite — good for walks and museums, brisk for swimming unless you like it cold. Four days is a harbor day, a coastal-walk day, a neighborhood-food day, and one Blue Mountains or northern-beaches excursion, not a lap of every icon.',
    visitorProfile:
      'For travelers who will pay for a well-placed bed and who would rather swim and ride a ferry than collect viewpoints from a coach.',
    climate: 'mediterranean',
    coordinates: { lat: -33.8688, lng: 151.2093 },
    airport: 'SYD — Sydney Kingsford Smith',
    timezone: 'Australia/Sydney',
    language: 'English',
    currency: 'AUD',
    walkability: 4,
    crowdLevel: 4,
    altitudeMeters: 58,
    costs: [230, 420, 900],
    gettingThere:
      'Kingsford Smith sits south of the CBD with trains, taxis, and rideshares to the city and eastern suburbs. International and domestic terminals are a short internal transfer apart.',
    gettingAround:
      'Opal card trains, buses, and ferries are the system. Walk Circular Quay to the Rocks. Buses and the coastal path handle Bondi and Coogee. A car is more friction than help inside the city.',
    highlights: [
      highlight('Ferry to Manly', 'The harbor is the attraction. Sit outside, then swim or walk the Corso and the ocean beach.', 'Half day'),
      highlight('Bondi to Coogee coastal walk', 'Headlands, ocean pools, and a string of bays. Start at Bondi early in January before the path clogs.', '3 hours'),
      highlight('Sydney Opera House precinct', 'Walk the forecourt, then decide if a tour or a performance is worth your money. The building is better from the water.', '2 hours'),
      highlight('The Rocks and Walsh Bay', 'Sandstone warehouses, a working wharf, and museums that explain the port. Weekday mornings are quieter.', '2 hours'),
      highlight('An ocean pool at dawn', 'Icebergs, Wylie’s, or a suburban baths. Salt water and a horizon line before the city starts arguing.', '1 hour'),
      highlight('Art Gallery of New South Wales', 'A strong collection and a new modern wing. Useful when a January westerly makes the coast unpleasant.', '2.5 hours'),
    ],
    food: [
      dish('Sydney rock oysters', 'Small, mineral, and best with almost nothing. Order a dozen at a harbor or beach bar.'),
      dish('A bakery meat pie', 'A working lunch, not a gastropub deconstruction. Eat it with sauce, standing up.'),
      dish('Haymarket yum cha', 'Late-morning carts in the Chinese quarter. A better use of a hot midday than another outdoor queue.'),
      dish('Grilled reef fish or bugs', 'Simple seafood on the water. Ask what came in that morning.'),
      dish('Inner-west Vietnamese or Lebanese', 'Marrickville and surrounding streets outcook many harbor-view rooms. Go for dinner and a walk.'),
    ],
    nearby: [
      nearby('Blue Mountains', 'Escarpment walks and cooler air. Katoomba is the usual base; start early to beat coach parks.', '2 hours by train'),
      nearby('Royal National Park', 'Coastal heath and swimming holes south of the city. A wilder day than another eastern-suburbs beach.', '90 minutes by train and walk'),
      nearby('Hunter Valley', 'A wine day inland. Better if you tour rather than drive after tastings.', '2 hours by car'),
      nearby('Northern Beaches beyond Manly', 'Longer sand and a slower pulse. A bus or ferry-plus-bus day if you want space.', '60–90 minutes'),
    ],
    itinerary: [
      day('Harbor first', 'Circular Quay walk and Opera House precinct at opening.', 'Ferry to Manly and a swim.', 'Rocks or Walsh Bay dinner.'),
      day('Coast path', 'Bondi to Coogee while the light is kind.', 'Ocean pool and a late lunch.', 'Inner-west dinner away from the waterfront markup.'),
      day('City rooms and food', 'Art Gallery or the Australian Museum.', 'Haymarket yum cha or a long market wander.', 'A booked table you actually want.'),
      day('One escape or buffer', 'Blue Mountains or a second beach suburb.', 'Back with slack.', 'Airport-aware evening.'),
    ],
    packing: [
      pack('Reef-safe sunscreen and a hat', 'January sun on pale sandstone and water is relentless.'),
      pack('Swimwear and a pack towel', 'Ocean pools and harbor beaches are part of the daily plan, not a side trip.'),
      pack('Light rain shell', 'Southerly changes soak you even in midsummer.'),
    ],
    tips: [
      'Sleep near a ferry or a coastal bus, not in a cheap room that costs you an hour each morning.',
      'Book Opera House seats if you want the interior; the exterior is free and crowded.',
      'January humidity argues for dawn swims and indoor middays.',
      'Ferries are transport, not a cruise product. Use them like locals and sit outside.',
    ],
    warnings: [
      'Rip currents kill swimmers every summer. Swim between the flags and ask the lifeguard if the break looks wrong.',
      'Keep bags zipped at Circular Quay and Bondi; crowded waterfronts attract quick hands.',
    ],
    bestMonths: ['March', 'April', 'September', 'October', 'November'],
    tags: ['harbor', 'ferries', 'ocean-pools', 'beaches', 'seafood'],
  },
  {
    id: 'wellington',
    name: 'Wellington',
    country: 'New Zealand',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['city', 'food', 'culture'],
    stayDays: 3,
    blurb:
      'A compact harbor capital with museums, hillside walks, and a food scene dense enough for a long weekend without changing hotels.',
    tagline: 'A windy harbor bowl where museums, coffee, and hill paths sit in one walkable grid',
    overview:
      'Wellington is a small capital pressed between harbor and hills, walkable if you accept wind and steep streets. January is summer: festivals, long evenings on the waterfront, and a southerly that can still make you wear a jacket to dinner. June to August is the short, sharp winter — good for Te Papa and broth, less good for the hill lookouts. Three days covers the museum, Cuba Street, a cable-car ridge, and a Zealandia or day-bay outing. You do not need a car in town; you need a layer that actually blocks wind.',
    visitorProfile:
      'Best for travelers who like compact capitals, serious coffee, and a museum that can swallow a wet afternoon without feeling like filler.',
    climate: 'oceanic',
    coordinates: { lat: -41.2865, lng: 174.7762 },
    airport: 'WLG — Wellington Airport',
    timezone: 'Pacific/Auckland',
    language: 'English, te reo Māori',
    currency: 'NZD',
    walkability: 5,
    crowdLevel: 2,
    altitudeMeters: 16,
    costs: [180, 320, 650],
    gettingThere:
      'The airport is a short taxi or airport-bus ride south of the CBD — unusually close for a capital. Domestic flights from Auckland and Christchurch are frequent. The Interislander and Bluebridge ferries arrive from Picton.',
    gettingAround:
      'Walk the waterfront and Cuba Street. Buses climb the hills. The cable car is both transit and a lookout. A car helps only for Wairarapa wine or a Kapiti beach day.',
    highlights: [
      highlight('Te Papa Tongarewa', 'The national museum done as a living building, not a trophy case. Give it a half day and skip the urge to see every floor.', '3 hours'),
      highlight('Cuba Street and the inner city', 'Bookshops, cheap eats, and a weekend bucket fountain. The city’s social spine.', '2 hours'),
      highlight('Cable car to Kelburn and the Botanic Garden', 'A ridge view, then a downhill wander through planted slopes back to the harbor.', '2 hours'),
      highlight('Zealandia ecosanctuary', 'A fenced valley of birds you will not see on the waterfront. Twilight tours change the soundtrack.', '3 hours'),
      highlight('Mount Victoria / Tangi Te Keo lookout', 'A short, steep climb and a harbor map at your feet. Go when the wind is merely strong, not dangerous.', '90 minutes'),
      highlight('Waterfront at golden hour', 'Wharves, the lagoon, and office workers walking home into the gale. The city’s best free show.', '1 hour'),
    ],
    food: [
      dish('A carefully made flat white', 'Wellington treats coffee as infrastructure. Sit once, properly, then stop hopping.'),
      dish('Whitebait in season', 'A West Coast and local-river luxury. Fritters, lemon, and no extra garnish.'),
      dish('Kapiti or other local cheese', 'Soft rinds and aged cheddars that show up on waterfront boards.'),
      dish('Craft beer on Cuba or Ghuznee', 'A small-city pouring culture. One or two glasses, then dinner.'),
      dish('Kūmara, done simply', 'Sweet potato as a side or a soup. More honest than another imported burger.'),
    ],
    nearby: [
      nearby('Days Bay and Eastbourne', 'A harbor ferry to a beach suburb. Summer swimming if the wind allows.', '25 minutes by ferry'),
      nearby('Martinborough', 'A compact wine village over the hill. Better as a tour or an overnight than a rushed drive.', '90 minutes by car'),
      nearby('Kāpiti Coast', 'Long beaches and a slower pulse north of town.', '50 minutes by train or car'),
      nearby('Picton via ferry', 'The South Island door if you are continuing. The crossing is a day, not an errand.', '3.5 hours by ferry'),
    ],
    itinerary: [
      day('Waterfront and Te Papa', 'Harbor walk in the morning calm.', 'Te Papa until your feet complain.', 'Cuba Street dinner.'),
      day('Hills and birds', 'Cable car and Botanic Garden.', 'Zealandia or Mount Victoria.', 'Waterfront evening if the wind drops.'),
      day('Bay or buffer', 'Days Bay ferry or a neighborhood wander.', 'Bookshops and a long coffee.', 'Airport-close supper; the flight is short but wind delays happen.'),
    ],
    packing: [
      pack('A real windproof layer', 'The southerly is the climate. A fashion coat will not do.'),
      pack('Grippy shoes', 'Hill paths and wet wooden wharves.'),
      pack('A compact umbrella that can fail', 'Have a hood as backup; umbrellas invert here for sport.'),
    ],
    tips: [
      'Book Zealandia twilight if you care about kiwi; daytime is still excellent for other birds.',
      'January festivals fill rooms. Winter rooms are cheaper and the museum is emptier.',
      'The airport’s closeness is a gift. Still leave slack when a southerly is forecast.',
      'You can eat well without a degustation. Follow the streets, not the hotel concierge list.',
    ],
    warnings: [
      'Gusts on ridges and the waterfront can knock you off balance. Skip the lookout in a gale warning.',
      'Earthquake awareness is part of living here. Know the drop-cover-hold basics in a tall building.',
    ],
    bestMonths: ['December', 'January', 'February', 'March'],
    tags: ['harbor', 'museums', 'coffee', 'hills', 'wind'],
  },
  {
    id: 'rotorua',
    name: 'Rotorua',
    country: 'New Zealand',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['culture', 'hiking', 'wildlife'],
    stayDays: 3,
    blurb:
      'Geothermal parks, forest walks, and Māori cultural venues sit around a lake basin, with short drives to further thermal fields.',
    tagline: 'Steam vents, redwoods, and a lake town that asks you to slow down for protocol',
    overview:
      'Rotorua is a lake town on an active geothermal field, with sulphur on the wind and walking tracks through both planted redwoods and living Māori communities. January is summer: long days, busy parks, and warm lake edges. Winter mornings can frost even when the steam looks tropical. Three days is enough for a cultural venue done properly, a geothermal reserve, and a forest or crater-lake walk — not a checklist of every paid steam field. The wildlife is birds, trout, and the occasional lake bird colony, plus the living landscape itself.',
    visitorProfile:
      'For travelers who will sit through a pōwhiri with respect, walk in steam without treating it as a theme park, and skip the fake village photograph.',
    climate: 'oceanic',
    coordinates: { lat: -38.1368, lng: 176.2497 },
    airport: 'ROT — Rotorua Airport',
    timezone: 'Pacific/Auckland',
    language: 'English, te reo Māori',
    currency: 'NZD',
    walkability: 3,
    crowdLevel: 3,
    altitudeMeters: 280,
    costs: [170, 310, 640],
    gettingThere:
      'Rotorua Airport has domestic flights from Auckland and Wellington. Many visitors drive from Auckland in about three hours. InterCity coaches also run the corridor.',
    gettingAround:
      'The town center is walkable; parks and forests need a car, bike, or tour. Local buses are thin. Book cultural evenings with transport if you are not driving after dark.',
    highlights: [
      highlight('Te Puia or a licensed living village evening', 'Craft, geothermal features, and a hāngī when it is offered as hospitality, not a buffet stunt. Follow the protocol you are given.', '4 hours'),
      highlight('Whakarewarewa Forest redwoods', 'Tall trees, well-built trails, and a night walk when the lights are on. Share the paths with riders; keep left.', '2 hours'),
      highlight('Wai-O-Tapu or Waimangu thermal reserve', 'Champagne pools, craters, and boardwalks through a working volcanic system. Go at opening for color and fewer buses.', '3 hours'),
      highlight('Lake Rotorua waterfront and Government Gardens', 'A calmer hour among bowling lawns and bathhouse architecture. Useful between steam stops.', '90 minutes'),
      highlight('Kuirau Park steam on a free path', 'Mud pools and hot ground inside town. Stay on the marked paths; the ground is not a shortcut.', '45 minutes'),
      highlight('Trout at a stream or lake edge', 'Rainbow trout in clear water, sometimes so tame they look staged. A hatchery visit explains the region’s fishing culture.', '1 hour'),
    ],
    food: [
      dish('Hāngī', 'Earth-oven meat and vegetables when a venue or family cooks it properly. The flavor is smoke and steam, not barbecue sauce.'),
      dish('Rēwena bread', 'A fermented-potato sourdough. Eat it with butter while it is still warm.'),
      dish('Lake trout', 'Pan-fried or smoked. A regional plate that matches the water you have been walking beside.'),
      dish('Horopito seasoning', 'A native pepper used on meat and vegetables. Ask when it is local, not a dusty shaker.'),
      dish('A boil-up', 'Pork, greens, and doughboys in broth. A home dish that appears on a few honest menus.'),
    ],
    nearby: [
      nearby('Wai-O-Tapu Thermal Wonderland', 'The colored terraces south of town. Pair with a cave or forest stop rather than two steam parks in a row.', '30 minutes by car'),
      nearby('Lake Taupō', 'A larger volcanic lake and river walks. An easy add if you are driving the plateau.', '60 minutes by car'),
      nearby('Waitomo Caves', 'Glowworms and limestone. A full extra day if you continue west, not a squeeze after a hāngī night.', '90 minutes by car'),
      nearby('Ōrākei Kōrako', 'A quieter geothermal valley reached by a short boat. Worth it if the main parks feel like a queue.', '45 minutes by car'),
    ],
    itinerary: [
      day('Town steam and gardens', 'Kuirau Park and the waterfront.', 'Government Gardens and a museum hour.', 'Booked cultural evening; do not arrive late.'),
      day('Color and forest', 'Wai-O-Tapu or Waimangu at opening.', 'Whakarewarewa redwoods in the afternoon.', 'Simple dinner in town.'),
      day('Water or onward', 'Lake edge, trout, or a short crater walk.', 'Pack and a last soak if your lodging has one.', 'Drive or fly with slack.'),
    ],
    packing: [
      pack('Shoes you can wash', 'Silica and mud find mesh sneakers. Closed shoes on boardwalks.'),
      pack('A layer that can take sulphur smell', 'It clings to wool. Pack something you do not mind airing out.'),
      pack('Swimwear for a mineral soak', 'Many lodgings and some public pools are part of the stay.'),
    ],
    tips: [
      'One excellent cultural booking beats three ticketed steam fields.',
      'January is busy. Winter has fewer coaches and colder steam plumes that photograph well.',
      'Ask before you photograph people or carved houses. Permission is the point.',
      'Stay on boardwalks. Thin crust has injured visitors who wanted a closer shot.',
    ],
    warnings: [
      'Geothermal water and ground can burn. Children and drones need closer supervision than you think.',
      'Sulphur aggravates some respiratory conditions. If that is you, sleep slightly out of the lowest steam pockets.',
    ],
    bestMonths: ['November', 'December', 'January', 'February', 'March'],
    tags: ['geothermal', 'māori', 'forest', 'lakes', 'trout'],
  },
  {
    id: 'cairns',
    name: 'Cairns',
    country: 'Australia',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['beach', 'wildlife', 'hiking'],
    stayDays: 4,
    blurb:
      'A tropical port for reef days and rainforest drives, with an esplanade lagoon when the open beaches are out of season.',
    tagline: 'A reef gateway with a lagoon promenade and a rainforest sitting on the ranges behind',
    overview:
      'Cairns is a low-rise port facing a muddy tidal foreshore, useful because the reef and the Wet Tropics sit within a day. January is high summer and wet season: humid, green, and prone to afternoon storms and stinger patrols. May to October is the dry, clearer window most visitors want. Four days should be one outer-reef day, one rainforest day, and two slower esplanade or island-edge days — not three consecutive 4 a.m. boat alarms. Wildlife means reef fish, cassowaries if you are lucky and careful in the Daintree, and a lot of fruit bats at dusk.',
    visitorProfile:
      'For travelers who will accept a working tropical city as a base, and who would rather do one excellent reef day than stack every island brand.',
    climate: 'tropical',
    coordinates: { lat: -16.9186, lng: 145.7781 },
    airport: 'CNS — Cairns Airport',
    timezone: 'Australia/Brisbane',
    language: 'English',
    currency: 'AUD',
    walkability: 3,
    crowdLevel: 3,
    altitudeMeters: 7,
    costs: [190, 350, 740],
    gettingThere:
      'Cairns Airport is a short taxi or bus hop from the esplanade, with domestic flights from the southern capitals and some international Pacific and Asian links. The coastal train from Brisbane is a long scenic alternative.',
    gettingAround:
      'The esplanade and CBD are walkable. Reef boats leave from the marina. Kuranda and the northern beaches need a bus, tour, or rental car. Self-drive the Captain Cook Highway only if you like concentrated scenery and careful overtaking.',
    highlights: [
      highlight('Outer reef day from the marina', 'Coral gardens and a glass of dry-season visibility if you pick the right operator. January can still be beautiful between storms.', 'Full day'),
      highlight('Esplanade lagoon at dusk', 'A swimming hole on the foreshore when the open water is stinger season. Fruit bats leave the trees as the light goes.', '90 minutes'),
      highlight('Kuranda railway or skyrail', 'A ridge of rainforest and a village that is touristy and still worth the canopy view. Do one direction by rail if you can.', 'Half day'),
      highlight('Green Island or a closer cay', 'A shorter reef day if a full outer crossing feels like too much boat.', '6 hours'),
      highlight('Boardwalk in the Wet Tropics', 'Boardwalks near Lake Barrine or a northern forest short walk. Listen more than you hike.', '2 hours'),
      highlight('Northern beaches afternoon', 'Palm Cove or Trinity for a swim in a netted enclosure and a slower meal.', '3 hours'),
    ],
    food: [
      dish('Barramundi', 'The Queensland plate. Grilled, with little in the way. Ask if it is wild or farmed if you care.'),
      dish('Mud crab', 'Messy, sweet, and priced as a celebration. Share it.'),
      dish('Mango and tropical fruit in season', 'Summer wet-season fruit is a reason January is not only rain. Eat it at a market stall.'),
      dish('Reef fish of the day', 'Trevally or coral trout when the boat cook is honest. Simple lemon and a salad.'),
      dish('A tray of cooked prawns', 'Esplanade takeaway, newspaper optional. A better dinner than another hotel buffet.'),
    ],
    nearby: [
      nearby('Great Barrier Reef pontoon or island', 'The reason most people fly here. Weather and stinger seasons shape the day more than the brochure.', '45–90 minutes by boat'),
      nearby('Kuranda and the Barron Gorge', 'Rail, skyrail, and a village in the ranges. Easy as a packaged day.', '30 minutes to the base, then the ride'),
      nearby('Daintree and Cape Tribulation', 'Lowland rainforest meeting reef. A long day or an overnight; watch for cassowaries on the road.', '2 hours by car'),
      nearby('Atherton Tablelands', 'Craters, waterfalls, and cooler air. A good wet-season alternative when the coast is flooding.', '90 minutes by car'),
    ],
    itinerary: [
      day('Esplanade and orientation', 'Lagoon swim and a marina wander.', 'A short forest or garden walk if the heat allows.', 'Bats and a prawn dinner.'),
      day('Reef', 'Boat at the hour you booked. Follow the briefing.', 'Snorkel the best visibility window.', 'Early night; sun and swell fatigue are real.'),
      day('Rainforest', 'Kuranda or a Tablelands loop.', 'Waterfall or crater lake.', 'Quiet evening in town.'),
      day('Beach suburb or Daintree buffer', 'Northern beaches or the start of a longer north drive.', 'Pack with slack for storms.', 'Flight that is not the last of the day in wet season.'),
    ],
    packing: [
      pack('Stinger suit in November–May', 'Box jellyfish season is not a rumor. Many boats supply suits; bring your own if you want a sure fit.'),
      pack('Reef-safe sunscreen and a rash top', 'Tropical sun through water burns faster than you plan.'),
      pack('Dry bag and a light rain shell', 'January storms arrive on a timer. Keep the camera dry.'),
    ],
    tips: [
      'Pick one reef day and protect it with a buffer. Boats cancel in rough weather.',
      'The esplanade lagoon is the city beach. The open foreshore is tidal mud, not a swimming failure.',
      'Dry season (May–October) is easier. January is lush, cheaper, and operationally messier.',
      'Cassowaries are dangerous if you approach or feed them. Stay in the car if one is on the road.',
    ],
    warnings: [
      'Marine stingers and crocodiles are seasonal and locational facts, not adventure flavor. Obey the signs.',
      'Cyclone watches in January–March can freeze boats and close roads. Build slack into international connections.',
    ],
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    tags: ['reef', 'rainforest', 'esplanade', 'tropics', 'boats'],
  },
  {
    id: 'perth',
    name: 'Perth',
    country: 'Australia',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['beach', 'city', 'food'],
    stayDays: 4,
    blurb:
      'Swan River parks, Indian Ocean beaches, and a ferry to a car-free island sit close enough to mix city and salt water without rushing.',
    tagline: 'A bright river city facing a cold, clean ocean and a long run of white-sand suburbs',
    overview:
      'Perth is a low, sunny grid on the Swan, with Kings Park on the scarp and beaches a short train or bus west. January is dry midsummer: hot inland, sea-breezed on the coast, and the opposite of a northern January. June to August is the wet winter — green parks, fewer swimmers, and a good time for museums and Fremantle pubs. Four days covers the park and river, a Cottesloe or Scarborough swim, a Fremantle day, and Rottnest if the ferry seats remain. Isolation is part of the mood; you flew a long way for light and water, not for a dense old town.',
    visitorProfile:
      'For travelers who want beach days attached to a real city, and who will take the ferry to an island rather than another shopping street.',
    climate: 'mediterranean',
    coordinates: { lat: -31.9505, lng: 115.8605 },
    airport: 'PER — Perth Airport',
    timezone: 'Australia/Perth',
    language: 'English',
    currency: 'AUD',
    walkability: 4,
    crowdLevel: 2,
    altitudeMeters: 32,
    costs: [190, 350, 720],
    gettingThere:
      'Perth Airport has international and domestic terminals a short transfer from the CBD by Airport Line train or taxi. Long-haul flights from Asia, Africa, and the eastern states make this the west-coast hinge.',
    gettingAround:
      'Trains to Fremantle and the northern beaches, buses along the coast, and a walkable riverfront. Ferries to Rottnest leave from the harbor or Hillarys. A car helps for the hills and Margaret River, not for downtown parking.',
    highlights: [
      highlight('Kings Park at the scarp', 'A planted plateau over the river and city. Sunset is the local ritual; mornings are cooler in January.', '2 hours'),
      highlight('Cottesloe Beach and the Indiana precinct', 'Clear water, a grass terrace, and a swim before the afternoon wind. Weekdays beat Sunday crowds.', '3 hours'),
      highlight('Fremantle markets and maritime streets', 'A port town with limestone, convict bones, and a better lunch scene than the CBD. Go on a market day if you can.', 'Half day'),
      highlight('Rottnest Island / Wadjemup', 'Bikes, bays, and quokkas that are wild animals, not props. Book the ferry; do not chase animals for a photo.', 'Full day'),
      highlight('Swan River foreshore walk or ferry', 'Black swans, city skyline, and a breeze that makes January heat usable.', '90 minutes'),
      highlight('An ocean sunset from Scarborough or City Beach', 'A different, longer beach if Cottesloe feels like a postcard queue.', '2 hours'),
    ],
    food: [
      dish('Western rock lobster', 'Crayfish of the west coast. A split grilled tail is enough; skip the heavy cream.'),
      dish('Fremantle fish and chips', 'Eaten on the wharf with seagulls as a given. Simple batter, local catch.'),
      dish('A west-coast flat white', 'The coffee culture is quieter than the southeastern capitals and still serious.'),
      dish('Swan Valley or Margaret River wine', 'Fortifieds and verdelho upriver; cabernet and chardonnay farther south. One region per trip.'),
      dish('A summer stone-fruit breakfast', 'Peaches and mangoes in January markets. The seasonal argument for coming in the heat.'),
    ],
    nearby: [
      nearby('Rottnest Island', 'The island day. Bikes beat the hop-on bus if you can ride in heat.', '30–90 minutes by ferry'),
      nearby('Fremantle', 'Port streets and a maritime museum. A train ride, not a distant excursion.', '30 minutes by train'),
      nearby('Swan Valley', 'Cellar doors and river flats. Easy as a half-day if someone else drives.', '30 minutes by car'),
      nearby('Margaret River', 'A proper wine-and-surf add. Better as one or two nights than a punishing day drive.', '3 hours by car'),
    ],
    itinerary: [
      day('River and park', 'Kings Park in the morning cool.', 'Swan foreshore and the CBD grid.', 'Cottesloe sunset swim in summer.'),
      day('Fremantle', 'Train at a civilized hour.', 'Markets, prison tour or maritime museum — pick one.', 'Wharf dinner and the train back.'),
      day('Island', 'Rottnest ferry and a bike loop of a few bays.', 'Swim and a simple lunch.', 'Return on a ferry with slack.'),
      day('Second beach or valley', 'Scarborough or a Swan Valley half day.', 'Pack.', 'Airport-aware evening.'),
    ],
    packing: [
      pack('Strong sunscreen and a long-sleeve rash top', 'January UV on pale beaches is severe.'),
      pack('Swimwear and reef shoes optional', 'Rocks on some bays; sand at Cottesloe is enough.'),
      pack('A light winter layer if you come June–August', 'Wet and 16 degrees feels colder on the coast than the number.'),
    ],
    tips: [
      'January heat is dry. Start walks at 8am and treat 2pm as indoor or water time.',
      'Book Rottnest ferries in school holidays. Shoulder weeks are kinder.',
      'Fremantle on a Friday or Saturday has more music and more crowds; midweek is easier.',
      'Margaret River is a separate trip. Do not steal your only island day for it.',
    ],
    warnings: [
      'Rips and rare shark closures happen. Swim near flags and listen to patrols.',
      'Quokkas bite and get sick on human food. Fines exist for a reason.',
    ],
    bestMonths: ['March', 'April', 'September', 'October', 'November'],
    tags: ['beaches', 'kings-park', 'rottnest', 'fremantle', 'swan'],
  },
  {
    id: 'nadi',
    name: 'Nadi',
    country: 'Fiji',
    region: 'Oceania',
    budget: 'luxury',
    activities: ['beach', 'culture', 'food'],
    stayDays: 5,
    blurb:
      'A gateway town for island boats and resort beaches, with village visits and market mornings when you want time off the sand.',
    tagline: 'Palm flats and a busy airport town that only makes sense once you add a boat',
    overview:
      'Nadi is the dry-side gateway on Viti Levu: sugar-cane flats, a workaday town, and the marina that feeds the Mamanuca and Yasawa boats. January is wet-season summer in the South Pacific — hot, lush, and cyclone-aware — still swimmable between squalls. May to October is the drier, trade-wind stretch most resorts price as high season. Five days should include at least one outer-island or island-day, a town-and-market morning, and unhurried beach time, not a packed tour list. Luxury here is a well-run transfer and a room that handles humidity, not a city skyline.',
    visitorProfile:
      'For travelers who will pay for a boat and a good reef, and who can treat a village visit as a guest, not a costume moment.',
    climate: 'tropical',
    coordinates: { lat: -17.7765, lng: 177.4356 },
    airport: 'NAN — Nadi International',
    timezone: 'Pacific/Fiji',
    language: 'Fijian, Fiji Hindi, English',
    currency: 'FJD',
    walkability: 2,
    crowdLevel: 3,
    altitudeMeters: 13,
    costs: [220, 420, 950],
    gettingThere:
      'Nadi International is the main Fijian arrival point, a short drive from Denarau and the town. Many island resorts include a boat or seaplane transfer from here. Do not book a same-day outer-island connection after a long-haul delay.',
    gettingAround:
      'Taxis and resort shuttles cover Nadi and Denarau. Water taxis and high-speed cats run the Mamanucas. Local buses are cheap and slow. A rental car helps for the Coral Coast, not for island hopping.',
    highlights: [
      highlight('A Mamanuca island day', 'Clear water, a village landing if offered properly, and a snorkel before the afternoon wind. Sleep on the island if you can.', 'Full day'),
      highlight('Denarau marina at departure hour', 'The choreography of boats, bags, and greetings. Useful even if you only watch and then swim.', '1 hour'),
      highlight('Nadi produce market', 'Dalos, chili, and Indo-Fijian spice stalls. Go in the morning; it is a working market, not a craft set.', '90 minutes'),
      highlight('Garden of the Sleeping Giant', 'Orchid collections under the Sabeto hills. A quiet, planted contrast to the marina.', '2 hours'),
      highlight('A village visit with a sevusevu', 'Kava presentation and a conversation if your host sets it up. Dress modestly and follow the lead of the guide.', '3 hours'),
      highlight('Sunset on the western reefs', 'Dry-side skies earn their reputation in the cooler months. January sunsets can be theatrical between storms.', '1 hour'),
    ],
    food: [
      dish('Kokoda', 'Coconut-cured reef fish with citrus and chili. The national plate when the fish is fresh.'),
      dish('Lovo', 'Earth-oven meat and root crops at a resort or village night. Go for the method, not the fire-dancing add-ons.'),
      dish('Palusami', 'Taro leaves and coconut cream baked until soft. Rich, green, and easy to share.'),
      dish('Indo-Fijian roti and curry', 'A street-breakfast staple in town. Potato or chicken, eaten with your hands.'),
      dish('Cassava and dalo', 'Boiled staples that explain the market better than another burger at the resort pool.'),
    ],
    nearby: [
      nearby('Mamanuca Islands', 'The close island chain. Day trips work; overnight is better.', '30–90 minutes by boat'),
      nearby('Yasawa Islands', 'Farther, thinner, and more about village stays and long reefs.', '2–5 hours by boat or a short flight'),
      nearby('Lautoka', 'A sugar port with a Saturday market and fewer resort prices.', '30 minutes by car'),
      nearby('Coral Coast', 'A longer stretch of Viti Levu beach resorts and coastal villages toward Suva.', '90 minutes by car'),
    ],
    itinerary: [
      day('Land and slow down', 'Transfer and a swim. Do not book a village tour two hours after a long-haul.', 'Market or a garden if you still have legs.', 'Early night; humidity is tiring.'),
      day('Island water', 'Boat to a Mamanuca cay or resort.', 'Snorkel the morning window.', 'Sunset on the same sand if you stay out.'),
      day('Culture at a human pace', 'Garden of the Sleeping Giant or a highland lookout.', 'Town lunch and the market.', 'Quiet resort dinner.'),
      day('Village or second reef', 'Sevusevu visit if arranged.', 'Free afternoon in the water.', 'Kava only if you want it; it is not a drinking contest.'),
      day('Buffer', 'A last swim.', 'Do not cut the airport transfer fine in wet season.', 'Flight with slack for squalls.'),
    ],
    packing: [
      pack('Reef-safe sunscreen, hat, and a light long shirt', 'Equatorial sun plus reflection off the lagoon.'),
      pack('A sulu or modest cover-up', 'Village visits and some churches expect covered knees and shoulders.'),
      pack('After-bite and a dry bag', 'Sandflies at dusk and wet boat rides are standard.'),
    ],
    tips: [
      'Sleep near Denarau or on an island, not beside the airport road, unless you have a dawn flight.',
      'January is cheaper and greener. Travel insurance that mentions cyclones is not optional.',
      'Bula is a greeting, not a performance you owe on command. Return it when you mean it.',
      'One excellent boat day beats three rushed brand-name islands.',
    ],
    warnings: [
      'Cyclone season runs through the southern summer. Watch official advisories, not social media rumors.',
      'Coral cuts infect quickly. Wear reef shoes where the coral is shallow and clean wounds with care.',
    ],
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    tags: ['islands', 'reef', 'village', 'lagoon', 'tropics'],
  },
  {
    id: 'rarotonga',
    name: 'Rarotonga',
    country: 'Cook Islands',
    region: 'Oceania',
    budget: 'luxury',
    activities: ['beach', 'food', 'hiking'],
    stayDays: 5,
    blurb:
      'A single volcanic island you can circle in an hour, with a lagoon for swimming days and a cross-island track when you want shade and height.',
    tagline: 'A circled lagoon, a mountain spine, and night markets that replace a restaurant crawl',
    overview:
      'Rarotonga is one high island inside a continuous reef, with a coastal road, a mountainous interior, and a pace that punishes over-planning. January is wet-season summer: humid, green, and inside the South Pacific cyclone watch. The drier, breezier months run roughly May to October. Five days is a lagoon circuit, a cross-island walk, a night-market rotation, and time to do nothing — the luxury is space, not a skyline. Scooters are the local default and the main way visitors get hurt.',
    visitorProfile:
      'For travelers who want a beach week with one real walk, and who can enjoy a small island without needing a new excursion every morning.',
    climate: 'tropical',
    coordinates: { lat: -21.2294, lng: -159.7763 },
    airport: 'RAR — Rarotonga International',
    timezone: 'Pacific/Rarotonga',
    language: 'Cook Islands Māori, English',
    currency: 'NZD',
    walkability: 3,
    crowdLevel: 2,
    altitudeMeters: 4,
    costs: [230, 420, 880],
    gettingThere:
      'Rarotonga International is on the north coast, a short taxi from most lagoon lodgings. Flights typically come from Auckland, and sometimes from Tahiti or Honolulu depending on the season. Immigration is straightforward if your documents match the return ticket.',
    gettingAround:
      'The coastal bus runs clockwise and anticlockwise on a loose timetable. Scooters need a local permit. Bikes work on the flat coast. The interior tracks are walking, not riding.',
    highlights: [
      highlight('Muri Lagoon at mid-morning', 'Turquoise inside the reef, with motu on the horizon. Snorkel before the afternoon wind chops the surface.', '3 hours'),
      highlight('Cross-island track to Wigmore’s or the Needle', 'A steep, rooted climb through interior forest. Go with a guide if the river crossings are up in January.', '4 hours'),
      highlight('Aitutaki daydream, or stay on-island', 'The famous lagoon is a separate flight. If you stay on Rarotonga, treat Muri and the south coast as enough water.', 'Full day if you fly'),
      highlight('Punanga Nui or a night market', 'Grills, ika mata, and coconut bread. Rotate markets rather than booking every dinner.', '2 hours'),
      highlight('A quiet south-coast swim', 'Fewer scooters, longer sand, and a slower sunset. Weekdays feel almost private.', '2 hours'),
      highlight('Ara Metua inland road', 'A shaded, historic inner loop. Walk or cycle it when the coastal road feels like a circuit you have already done.', '90 minutes'),
    ],
    food: [
      dish('Ika mata', 'Coconut and citrus on raw reef fish. Order it early in the night-market line.'),
      dish('Rukau', 'Taro leaves in coconut cream. Green, rich, and easy to share.'),
      dish('Umu feast food', 'Earth-oven banana leaves and pork when a Sunday or resort umu is on. The method is the point.'),
      dish('Poke', 'A Cook Islands banana or pawpaw pudding, not a Hawaiian bowl. Soft, coconut-heavy, and local.'),
      dish('Fresh pawpaw and lime', 'Breakfast that explains why you came in the fruiting months. Buy it at a roadside stall.'),
    ],
    nearby: [
      nearby('Aitutaki', 'A world-class lagoon a short flight north. Worth two nights if you can split the week.', '45 minutes by air'),
      nearby('Muri motu snorkel circuit', 'Small islets inside the reef. A kayak or walking-and-swim morning.', '10–20 minutes from Muri'),
      nearby('Atiu', 'Caves, birds, and a slower island if you want a second flight.', '40 minutes by air'),
      nearby('Inland Needle and stream pools', 'The mountainous interior on the same island. A hike, not a transfer.', '30–60 minutes to the trail'),
    ],
    itinerary: [
      day('Lagoon and sleep', 'Swim at your nearest beach after the flight.', 'A slow coastal bus loop to learn the island.', 'Night market if one is on.'),
      day('Water morning', 'Muri snorkel while the lagoon is glass.', 'Shade and a long lunch.', 'South-coast sunset.'),
      day('Interior walk', 'Cross-island track with an early start.', 'Recovery swim.', 'Simple dinner; legs will complain.'),
      day('Empty hours', 'Ara Metua walk or a second bay.', 'Read, swim, do not book a tour to feel productive.', 'Another market or a beach barbecue.'),
      day('Buffer', 'Last snorkel.', 'Scooter return and airport slack.', 'Evening flight or a last swim if you leave the next dawn.'),
    ],
    packing: [
      pack('Reef shoes and a rash top', 'Coral and tropical sun are the two constants.'),
      pack('Mosquito protection', 'Wet-season evenings inland are busy with insects.'),
      pack('Closed shoes for the cross-island track', 'Roots and mud, especially in January rain.'),
    ],
    tips: [
      'Sunday is quiet. Plan a beach and a book, not a shopping list.',
      'Hire a scooter only after the local license test, and assume other visitors are inexperienced.',
      'Five nights lets the island slow you down. Three nights feels like a layover with better water.',
      'Ask before photographing people or marae. It is a small place and memory is long.',
    ],
    warnings: [
      'Scooter crashes are the common visitor emergency. Helmets are not optional.',
      'Cyclone season can disrupt flights. Keep a buffer before any locked-in onward travel.',
    ],
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    tags: ['lagoon', 'night-market', 'cross-island', 'reef', 'small-island'],
  },
  {
    id: 'christchurch',
    name: 'Christchurch',
    country: 'New Zealand',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['city', 'hiking', 'food'],
    stayDays: 3,
    blurb:
      'A rebuild city with river loops and nearby peninsula and alpine day trips, useful as a South Island arrival rather than a one-night stop.',
    tagline: 'A river grid still rewriting itself, with hills and a volcanic peninsula on the doorstep',
    overview:
      'Christchurch is a low city on the Avon / Ōtākaro, still visibly mid-rebuild, with the Port Hills as a daily backdrop. January is Canterbury summer: long evenings, nor’west heat, and a good window for Banks Peninsula walks. Winter brings frost, fog, and a different, quieter city. Three days is a river-and-garden day, a Port Hills or Akaroa day, and a buffer that can become Arthur’s Pass if the weather is kind. The interest is the mix of new architecture, remaining heritage, and how quickly you can be on a crater-rim track.',
    visitorProfile:
      'For travelers entering or leaving the South Island who want a real city night plus one outdoor day, not a museum-only layover.',
    climate: 'oceanic',
    coordinates: { lat: -43.5321, lng: 172.6362 },
    airport: 'CHC — Christchurch Airport',
    timezone: 'Pacific/Auckland',
    language: 'English, te reo Māori',
    currency: 'NZD',
    walkability: 4,
    crowdLevel: 2,
    altitudeMeters: 20,
    costs: [170, 300, 620],
    gettingThere:
      'Christchurch Airport is the South Island’s main hub, with a bus and taxi run to the center. Long-distance buses and the TranzAlpine train leave from town. Many rental-car road trips start here.',
    gettingAround:
      'The central rebuild zone is walkable and bike-friendly. Buses reach the hills and suburbs. A car is the clean way to Akaroa or the Alps. The heritage tram is a loop, not a transit network.',
    highlights: [
      highlight('Ōtākaro / Avon river punting or a bank walk', 'Willows, new bridges, and a pace that ignores the rebuild cranes. Walk it if you do not want the boat.', '90 minutes'),
      highlight('Christchurch Botanic Gardens', 'A planted core that survived better than many streets. January flowers and shade; winter structure and birds.', '2 hours'),
      highlight('Port Hills ridge', 'Crater-rim tracks above the city and Lyttelton Harbour. Start early if a nor’wester is forecast.', '3 hours'),
      highlight('Riverside Market and the new inner city', 'A food hall that shows how the center eats now. Useful on a cold or windy afternoon.', '90 minutes'),
      highlight('Quake City or a rebuild walking tour', 'A clear, bounded way to understand 2010–11 without turning every ruin into a souvenir.', '90 minutes'),
      highlight('Lyttelton harbor town', 'A tunnel or hill road to a port with better coffee and a different weather. Time a return before the last bus.', 'Half day'),
    ],
    food: [
      dish('A Saturday farmers’ market haul', 'Cheese, pastry, and stone fruit in summer. Riccarton or a central market depending on the week.'),
      dish('Canterbury lamb', 'A regional default done well at a few rooms. Lunch after a hill walk.'),
      dish('Waipara wine', 'Riesling and pinot a short drive north. One cellar door is enough.'),
      dish('Craft beer in the rebuild grid', 'A small-city pouring scene. Pair with a simple plate, not a second flight.'),
      dish('Cheese from the plains', 'Local wheels that travel to a river picnic better than another café sandwich.'),
    ],
    nearby: [
      nearby('Akaroa and Banks Peninsula', 'A French-accented harbor village and crater walks. The best full day from the city.', '90 minutes by car'),
      nearby('Arthur’s Pass', 'Alpine beech and a kea chance. A long day; weather closes the point of going.', '2 hours by car or the TranzAlpine'),
      nearby('Hanmer Springs', 'A thermal-village day north. Softer than the pass if legs are tired.', '90 minutes by car'),
      nearby('Lyttelton', 'The working port over the hill. A half day with a harbor walk.', '20 minutes by tunnel'),
    ],
    itinerary: [
      day('River city', 'Botanic Gardens and a river loop.', 'Riverside Market and a rebuild walk.', 'Inner-city dinner.'),
      day('Peninsula or hills', 'Akaroa if you have a car; Port Hills if you do not.', 'Harbor swim in January or a short crater walk.', 'Quiet night; sun and wind tire you.'),
      day('Alps, port, or buffer', 'Arthur’s Pass only with a clear forecast.', 'Otherwise Lyttelton and coffee.', 'Airport slack; nor’west gales delay flights.'),
    ],
    packing: [
      pack('Sun hat and a wind layer', 'January nor’westers are hot and abrasive; the hills are cooler and gusty.'),
      pack('Walking shoes with grip', 'Loess and basalt on the Port Hills get slick after rain.'),
      pack('A warm layer year-round', 'Clear winter nights frost hard on the plains.'),
    ],
    tips: [
      'Treat the rebuild as context, not a dark-tourism circuit.',
      'Akaroa is the day trip that feels like a different island. Start before 9am.',
      'The TranzAlpine is a journey, not a commute. Use it when you are continuing west.',
      'January school holidays fill Akaroa. Shoulder weeks are kinder.',
    ],
    warnings: [
      'Nor’west winds make ridges and airport approaches unpleasant. Check the forecast before a hill day.',
      'Aftershocks are rarer now but earthquake awareness still applies in older brick buildings.',
    ],
    bestMonths: ['December', 'January', 'February', 'March'],
    tags: ['rebuild', 'river', 'port-hills', 'peninsula', 'gardens'],
  },
  {
    id: 'broome',
    name: 'Broome',
    country: 'Australia',
    region: 'Oceania',
    budget: 'luxury',
    activities: ['beach', 'wildlife', 'culture'],
    stayDays: 4,
    blurb:
      'Red cliffs, a long cable beach, and tidal spectacles sit at the edge of the Kimberley, with pearling history still visible in town.',
    tagline: 'Red dust, a twenty-two-kilometre beach, and tides that rewrite the foreshore twice a day',
    overview:
      'Broome is a small pearling town on Roebuck Bay, famous for Cable Beach and for tides that expose mudflats the size of a suburb. The climate here is arid-tropical: a dry, bright winter (May to September) that most visitors want, and a wet, hot summer. January is that summer — cyclone-aware, humid, and often spectacular at last light, but a specialist month for heat and storms. Four days covers Cable Beach, a Yawuru-informed town walk, a dinosaur-print or cliff low tide, and one longer Kimberley add if the roads and boats are running. Luxury is a room with serious air-conditioning and a sunset that you do not have to share with a coach if you walk farther down the sand.',
    visitorProfile:
      'For travelers who will pay for distance and light, respect Traditional Owner guidance, and accept that wildlife includes crocodiles and camels for hire.',
    climate: 'arid',
    coordinates: { lat: -17.9614, lng: 122.2359 },
    airport: 'BME — Broome International',
    timezone: 'Australia/Perth',
    language: 'English, Yawuru',
    currency: 'AUD',
    walkability: 2,
    crowdLevel: 2,
    altitudeMeters: 19,
    costs: [240, 450, 920],
    gettingThere:
      'Broome Airport is close to town, with flights from Perth and seasonal links from the eastern states. The drive from the Pilbara or Darwin is a trip in itself, not a transfer.',
    gettingAround:
      'A rental car or scooter helps; the beach, Chinatown, and Gantheaume Point do not sit in one walking loop. Tours handle Horizontal Falls and the Dampier Peninsula. Taxis exist but are not a dense city fleet.',
    highlights: [
      highlight('Cable Beach sunset', 'Red sand, Indian Ocean, and a sky that goes theatrical. Walk away from the camel turnout if you want a quieter frame.', '2 hours'),
      highlight('Stairway to the Moon', 'A rising moon over exposed Roebuck Bay tidal steps, a few nights after full moon in the dry season. Check the local dates.', '2 hours'),
      highlight('Gantheaume Point at low tide', 'Red sandstone, turquoise water, and dinosaur prints in the rock platform when the tide allows.', '90 minutes'),
      highlight('Chinatown and the pearling story', 'Streets that still show a multicultural pearling port. A museum hour beats another jewelry window.', '2 hours'),
      highlight('A Yawuru country briefing or jetty walk', 'Roebuck Bay is living country. Start with interpretation, then the birds and mudflats make more sense.', '2 hours'),
      highlight('Willie Creek or a working pearl farm', 'The industry that built the town, seen as a process rather than a shop.', 'Half day'),
    ],
    food: [
      dish('Pearl meat', 'A local luxury when it is actually on the menu. Mild, slightly sweet, and easy to overcook — trust a kitchen that serves it often.'),
      dish('Barramundi', 'Grilled, with a view of mangroves if you can. The Kimberley plate.'),
      dish('Mango in the wet', 'January fruit if the season cooperates. A reason the hot months are not only endurance.'),
      dish('Chilli mud crab', 'A Broome celebration dish. Messy, shared, and priced accordingly.'),
      dish('Damper with golden syrup', 'Camp bread that still appears on sunset tours. Honest if it is fresh.'),
    ],
    nearby: [
      nearby('Horizontal Falls', 'A tidal spectacle reached by boat or seaplane. Weather and tides decide the day.', 'Half to full day by tour'),
      nearby('Dampier Peninsula / Cape Leveque', 'Red cliffs, remote communities, and a corrugated road. Go with time and permission, not as a dash.', '3 hours by car'),
      nearby('Willie Creek', 'Pearl farm and creek country north of town.', '40 minutes by car'),
      nearby('Gantheaume Point', 'The cliff and print platform at the south end of Cable Beach.', '15 minutes by car'),
    ],
    itinerary: [
      day('Beach and town', 'Cable Beach in the morning before the glare.', 'Chinatown and a pearling museum.', 'Sunset on the sand.'),
      day('Tides and stone', 'Gantheaume at a published low tide.', 'Rest through the hot middle — January especially.', 'Stairway to the Moon if the dates match; otherwise the bay at dusk.'),
      day('Water country', 'Willie Creek or a bay bird walk with interpretation.', 'Shade and a long lunch.', 'Quiet night; dust and light are tiring.'),
      day('Kimberley add or buffer', 'Horizontal Falls only if the tour is running.', 'Otherwise a second beach walk farther from the car park.', 'Airport slack in the wet.'),
    ],
    packing: [
      pack('Serious sun protection and electrolyte sachets', 'Arid glare plus tropical humidity in the wet. January heat is not a toughness test.'),
      pack('Insect repellent and covered evening shoes', 'Midges and hot sand at dusk.'),
      pack('Tide timetable and a torch', 'Rock platforms and moon nights are the point; phones die in glare.'),
    ],
    tips: [
      'Plan around tides more than opening hours.',
      'Dry season is easier. January is for people who like storms and empty beaches and who accept cancellations.',
      'Camel photos are optional. The beach is better a kilometer south.',
      'Ask about photography and access on Yawuru country. Some sites are not casual lookouts.',
    ],
    warnings: [
      'Saltwater crocodiles use the bay and creeks. Swim only where locals and signs say it is done.',
      'Cyclones and extreme UV are the two ways a Broome trip goes wrong. Heat stroke arrives faster than you expect.',
    ],
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    tags: ['cable-beach', 'tides', 'pearling', 'kimberley', 'red-cliffs'],
  },
  {
    id: 'auckland',
    name: 'Auckland',
    country: 'New Zealand',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['city', 'food', 'hiking'],
    stayDays: 3,
    blurb:
      'A harbor city of volcanic cones and ferry islands, useful as a food-and-walking base before you leave for smaller towns.',
    tagline: 'A sprawling isthmus of cones, ferries, and a waterfront that works if you pick one ridge',
    overview:
      'Auckland is a large, low city on a pinched isthmus, with maunga (volcanic cones) as public parks and ferries as the best way out. January is summer: beach weather on both coasts, busy ferries to Waiheke, and pohutukawa in flower. Winter is milder than the southern cities but wetter on the west coast. Three days is a waterfront-and-cone day, a Waiheke or west-coast day, and a neighborhood-food day — not a lap of every mall. Hike here means a short, steep scoria climb or a coastal track, not an alpine crossing.',
    visitorProfile:
      'For travelers who land here anyway and want the city to be more than an airport hotel, with one island or west-coast walk in the mix.',
    climate: 'oceanic',
    coordinates: { lat: -36.8509, lng: 174.7645 },
    airport: 'AKL — Auckland Airport',
    timezone: 'Pacific/Auckland',
    language: 'English, te reo Māori',
    currency: 'NZD',
    walkability: 3,
    crowdLevel: 3,
    altitudeMeters: 79,
    costs: [190, 350, 720],
    gettingThere:
      'Auckland Airport is the country’s main international gate, with a bus and taxi run north to the CBD. Domestic connections fan out from the same campus. Do not underestimate peak-hour traffic into town.',
    gettingAround:
      'Walk the waterfront. Use the inner-city link bus or a Hop card. Ferries to Devonport and Waiheke are the joy. A car helps for Piha; it hinders downtown. Cones are steep walks from surrounding streets.',
    highlights: [
      highlight('Maungawhau / Mount Eden or another maunga', 'A short, steep climb and a 360-degree map of the isthmus. Stay off any areas marked for restoration or tapu.', '90 minutes'),
      highlight('Waitematā waterfront and Wynyard', 'New promenades, working wharves, and a place to eat fish without leaving town.', '2 hours'),
      highlight('Ferry to Devonport', 'A village, a beach, and another cone if your legs allow. The ride is the attraction.', 'Half day'),
      highlight('Waiheke Island day', 'Bays, a ridge walk, and one vineyard lunch. Do not try to taste the whole island.', 'Full day'),
      highlight('Auckland Art Gallery or the War Memorial Museum', 'A wet-day backbone. The museum’s Māori courts need time and quiet.', '2.5 hours'),
      highlight('Domain wintergardens and the museum ridge', 'A planted pause between the CBD and the isthmus view.', '90 minutes'),
    ],
    food: [
      dish('A waterfront snapper or tarakihi', 'Simple grilled fish. Ask what was landed, not what the photographer styled.'),
      dish('Waiheke wine with a cheese board', 'Syrah and chardonnay a ferry away. One sitting, then a swim.'),
      dish('South Auckland or inner-west Pacific plates', 'Oka, chop suey, and coconut-rich dishes that reflect who actually lives here.'),
      dish('A serious city coffee', 'The daily standard. One good cup in a side street beats a waterfront chain.'),
      dish('Whitebait fritter in season', 'A national luxury that appears on a few Auckland menus when the run is on.'),
    ],
    nearby: [
      nearby('Waiheke Island', 'The island day most visitors want. Book ferries in January.', '40 minutes by ferry'),
      nearby('Piha and the Waitākere coast', 'Black sand and a serious west-coast swell. Go for the walk and the lookout, swim only if patrols say so.', '50 minutes by car'),
      nearby('Rangitoto Island', 'A scoria cone in the gulf. A full walk in summer heat; take water.', '25 minutes by ferry plus the climb'),
      nearby('Devonport', 'The close ferry village. Easy as a half day.', '15 minutes by ferry'),
    ],
    itinerary: [
      day('Cones and waterfront', 'Maungawhau in the morning.', 'Waterfront walk and a gallery or museum.', 'Neighborhood dinner, not the hotel restaurant.'),
      day('Island or west coast', 'Waiheke if you want wine and bays; Piha if you want surf and bush.', 'Do not stack both.', 'Ferry or car home before the last run.'),
      day('Second cone or buffer', 'Devonport or Rangitoto if legs remain.', 'Domain and a long coffee.', 'Airport traffic buffer; January Friday evenings clog.'),
    ],
    packing: [
      pack('Layers and a rain shell', 'West-coast weather ignores the city forecast. January still brings a wet southwest change.'),
      pack('Water and sun protection for cones', 'No shade on scoria in midsummer.'),
      pack('Swimwear', 'Bays on Waiheke and Devonport are part of the point in January.'),
    ],
    tips: [
      'Pick one maunga and walk it properly. Collecting cones from the car park is a lesser trip.',
      'January ferries to Waiheke fill. Book, then still arrive early.',
      'The city is sprawling. Sleep near a ferry or the inner grid.',
      'West-coast rips are not east-coast rips. Read the signs at Piha as if they apply to you.',
    ],
    warnings: [
      'Piha and other west-coast beaches have lethal rips. Swim only when lifeguards are on and where they indicate.',
      'Stay on marked paths on maunga; some slopes are culturally restricted or ecologically fragile.',
    ],
    bestMonths: ['December', 'January', 'February', 'March'],
    tags: ['harbor', 'volcanic-cones', 'ferries', 'waiheke', 'waterfront'],
  },
  {
    id: 'uluru',
    name: 'Uluru',
    country: 'Australia',
    region: 'Oceania',
    budget: 'luxury',
    activities: ['culture', 'hiking'],
    stayDays: 3,
    blurb:
      'A short stay on Anangu country built around dawn walks, cultural briefings, and the nearby domes of Kata Tjuta.',
    tagline: 'A single rock that holds a whole horizon, walked at the hours the heat allows',
    overview:
      'Uluru–Kata Tjuta is a national park on the lands of the Aṉangu, experienced from the resort village of Yulara rather than a conventional town. January is deep summer in the central desert: days that routinely pass 40°C, storm build-ups, and walks that must start at dawn or not at all. May to September is the humane window — cool nights, walkable days, and the season most people should book. Three days is a cultural-centre morning, a base walk or a shorter edge walk, a Kata Tjuta gorge, and a dawn or dusk viewing. Climbing the rock is closed; the walk around it is the point.',
    visitorProfile:
      'For travelers who will pay for access and heat management, listen more than they pose, and treat photography rules as law, not a suggestion.',
    climate: 'arid',
    coordinates: { lat: -25.3444, lng: 131.0369 },
    airport: 'AYQ — Ayers Rock Airport (Connellan)',
    timezone: 'Australia/Darwin',
    language: 'English, Pitjantjatjara, Yankunytjatjara',
    currency: 'AUD',
    walkability: 2,
    crowdLevel: 3,
    altitudeMeters: 863,
    costs: [320, 580, 1200],
    gettingThere:
      'Ayers Rock Airport is a short shuttle from Yulara, with flights from Sydney, Melbourne, and other capitals that change with the season. The drive from Alice Springs is a half-day on a sealed road; do not treat it as a casual errand in January heat.',
    gettingAround:
      'Resort shuttles and park buses cover the main car parks. A rental car gives dawn flexibility. There is no casual taxi culture. Walking is on marked park tracks only.',
    highlights: [
      highlight('Uluru base walk at opening', 'A circuit of waterholes, rock art shelters, and changing color. Start at the earliest gate time in any month; in January it is the only humane slot.', '3.5 hours'),
      highlight('Cultural Centre before the rock', 'Tjukurpa explained by Aṉangu voices. Do this first so the walk is not just geology.', '90 minutes'),
      highlight('Kata Tjuta Walpa Gorge', 'Domes, a cold wind even in summer, and a shorter walk than the Valley of the Winds when heat warnings are up.', '2 hours'),
      highlight('Dawn from a designated dune', 'The rock turning from charcoal to ochre. Arrive before the car park fills; leave without walking toward closed areas.', '90 minutes'),
      highlight('Field of Light after dark', 'A paid art installation on the desert floor. Optional, popular, and easier in the cooler months.', '2 hours'),
      highlight('Sunset at a signed viewing area', 'The last color and the first stars. Stay for the afterglow; the buses leave early.', '90 minutes'),
    ],
    food: [
      dish('Bush tomato and native herbs', 'Flavors introduced through a cultural or resort kitchen, not as a novelty dust. Ask what is local and in season.'),
      dish('Kangaroo, when it is offered well', 'Lean red meat that belongs to this country. A simple grill beats a heavy sauce.'),
      dish('Quandong or wild-peach notes', 'A desert fruit that appears in jams and desserts when kitchens bother. A taste, not a main.'),
      dish('Wattleseed in a breakfast or dessert', 'Nutty, roasted, and better in a small dose than a whole menu theme.'),
      dish('A dawn camp breakfast', 'Tea, fruit, and something hot after the viewing. Ritual more than cuisine, and part of the stay.'),
    ],
    nearby: [
      nearby('Kata Tjuta / the Olgas', 'A second massif west of Uluru. Give it its own morning.', '40 minutes by car'),
      nearby('Kings Canyon / Watarrka', 'A rim walk farther north. Better as an overnight than a brutal out-and-back in heat.', '3.5 hours by car'),
      nearby('Alice Springs', 'The nearest real town. A separate stay if you are overlanding, not a casual dinner run.', '4.5 hours by car'),
      nearby('Sunset and dawn dunes inside the park', 'Signed viewing areas a short drive from Yulara. The close “nearby” that still requires a park pass.', '15–25 minutes by car'),
    ],
    itinerary: [
      day('Arrive and listen', 'Cultural Centre after the shuttle and a rest if you flew in the heat.', 'Short edge walk only if the temperature allows.', 'Sunset viewing; drink water on the way back.'),
      day('The rock at dawn', 'Base walk or a ranger-guided section at opening.', 'Shade, pool, and a long indoor afternoon in January.', 'Field of Light or a quiet dinner.'),
      day('Kata Tjuta and buffer', 'Walpa Gorge or Valley of the Winds at dawn.', 'Pack and a last look from a dune.', 'Flight that is not tight against a heat delay.'),
    ],
    packing: [
      pack('More water capacity than you think and electrolytes', 'Dry heat plus walking. January is medically serious.'),
      pack('Long sun layers, a wide hat, and closed shoes', 'Sand, spinifex, and UV that burns through cloud.'),
      pack('A warm layer for May–August dawns', 'Desert nights drop hard in the good walking season.'),
    ],
    tips: [
      'Book the cooler months unless you specifically want storm light and empty paths — and you know how to cancel a walk.',
      'Photography restrictions at sacred sites are not optional. Put the camera down when the sign says so.',
      'The climb is closed. Planning to “just go up” is planning to break the law and Aṉangu request.',
      'Three nights is enough if you wake early. Two nights wastes the airfare on a single dawn.',
    ],
    warnings: [
      'Heat kills walkers here every summer. Park alerts close tracks; treat them as final.',
      'Drones, off-track walking, and souvenir rock-taking are illegal. Fines are real.',
    ],
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    tags: ['desert', 'anangu', 'kata-tjuta', 'dawn-walks', 'red-centre'],
  },
  {
    id: 'port-vila',
    name: 'Port Vila',
    country: 'Vanuatu',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['beach', 'culture', 'hiking'],
    stayDays: 4,
    blurb:
      'A harbor capital with market mornings, waterfall walks, and short boat hops to reefs, useful as a slower Melanesian beach stay.',
    tagline: 'A hillside harbor, a waterfront market, and reef days that start with a small boat',
    overview:
      'Port Vila climbs the hills above a sheltered harbor on Éfaté, with a waterfront market, a few good beaches a short drive out, and a cultural mix of Bislama, English, and French. January is wet-season summer in the southwest Pacific: hot, green, and cyclone-aware, with afternoon squalls that make waterfall walks louder. May to October is the drier, easier stretch. Four days covers the market and town, Mele Cascades or a ridge walk, a snorkel island, and a village or nakamal evening that you enter as a guest. This is not a mega-resort circuit; it is a small capital that still feeds itself from the water and the gardens behind it.',
    visitorProfile:
      'For travelers who want a beach week with a real market and a short hike, and who can handle humidity, Sunday quiet, and a slower boat timetable.',
    climate: 'tropical',
    coordinates: { lat: -17.7334, lng: 168.3273 },
    airport: 'VLI — Bauerfield International',
    timezone: 'Pacific/Efate',
    language: 'Bislama, English, French',
    currency: 'VUV',
    walkability: 3,
    crowdLevel: 2,
    altitudeMeters: 8,
    costs: [14000, 26000, 52000],
    gettingThere:
      'Bauerfield Airport is a short taxi ride from town, with flights from Auckland, Brisbane, Nadi, and Nouméa that change by season. Do not plan a same-afternoon outer-island hop after a delayed international arrival.',
    gettingAround:
      'Town taxis and buses (they are often vans) cover the harbor and nearby beaches. Boats run to Hideaway and other close reefs. A rental car helps for the island loop; roads can be rough after January rain.',
    highlights: [
      highlight('Port Vila waterfront market', 'Taro, island cabbage, and fish on ice. Go in the morning; it is how the town eats, not a craft bazaar.', '2 hours'),
      highlight('Mele Cascades', 'A paid waterfall walk through planted forest to swimming pools. Wear shoes that can get wet; January flow is stronger.', '3 hours'),
      highlight('Hideaway Island or a close reef', 'A short boat, a marine reserve, and a snorkel before the afternoon wind. The underwater post office is optional kitsch.', '4 hours'),
      highlight('A village visit on Éfaté', 'Gardens, cooking, and a conversation if a local operator sets it up. Dress modestly and pay the asked fee without bargaining theatre.', 'Half day'),
      highlight('Harbor swim at a town or Pango beach', 'Closer water when you do not want a boat. Check with locals after heavy rain.', '2 hours'),
      highlight('Ridge or coastal walk above the bay', 'A short hike with a view back to Iririki and the yacht fleet. Start early in the wet-season heat.', '2 hours'),
    ],
    food: [
      dish('Laplap', 'Grated root crop and coconut baked in leaves, sometimes with chicken or flying fox where it is legal and local. The national dish when it is made for a gathering.'),
      dish('Tuluk', 'A small laplap parcel with a meat filling, sold as a snack. Buy it where office workers buy it.'),
      dish('Simboro', 'Island cabbage rolled around grated cassava and coconut. Green, rich, and easy to share.'),
      dish('Grilled wahoo or reef fish', 'Harbor catch with lime and chili. Ask what came in that morning.'),
      dish('A nakamal shell of kava', 'Not a meal, but the evening social drink. One or two shells, quiet conversation, no shouting.'),
    ],
    nearby: [
      nearby('Hideaway Island', 'The close snorkel island. Easy as a half day from town.', '20 minutes by road and boat'),
      nearby('Mele Cascades', 'The waterfall most visitors use as their hike. Morning light is kinder.', '25 minutes by car'),
      nearby('Pele or another north-coast island', 'A quieter reef and village day if the boat is running.', '60–90 minutes by boat'),
      nearby('Tanna', 'Volcano country on a separate island. A two-night add, not a Port Vila day trip.', '40 minutes by air'),
    ],
    itinerary: [
      day('Harbor and market', 'Waterfront market at opening.', 'Town walk and a harbor swim.', 'Early dinner; humidity after a long-haul is real.'),
      day('Waterfall and shade', 'Mele Cascades while the morning is cooler.', 'Long lunch and a rest through the squall hour.', 'Nakamal or a quiet lodging night.'),
      day('Reef', 'Hideaway or a similar close island.', 'Snorkel the clear window.', 'Sunset on the harbor.'),
      day('Village or second walk', 'A booked village morning or a ridge hike.', 'Pack with slack for wet-season roads.', 'Flight that is not the last of the day in cyclone watch weeks.'),
    ],
    packing: [
      pack('Reef-safe sunscreen, a rash top, and reef shoes', 'Tropical sun and shallow coral are the daily pair.'),
      pack('A light rain shell and dry bag', 'January squalls soak bags on open boats.'),
      pack('A modest wrap for villages and town', 'Covered knees and shoulders are basic courtesy outside the resort pool.'),
    ],
    tips: [
      'Carry a mix of vatu cash; cards fail in small vans and at some market stalls.',
      'Sunday is quiet. Plan a beach and a book, not a shopping circuit.',
      'One excellent boat day and one waterfall day is enough. Do not stack Tanna onto four nights.',
      'Bislama greetings go a long way. Learn a few words and use them without performing.',
    ],
    warnings: [
      'Cyclone season can close the airport and flatten gardens. Insurance and a flexible ticket matter in January–March.',
      'Strong sun and coral cuts are the common medical stories. Clean wounds and drink more water than the flight suggested.',
    ],
    bestMonths: ['May', 'June', 'July', 'August', 'September'],
    tags: ['harbor', 'market', 'waterfall', 'reef', 'melanesia'],
  },
  {
    id: 'dunedin',
    name: 'Dunedin',
    country: 'New Zealand',
    region: 'Oceania',
    budget: 'comfortable',
    activities: ['wildlife', 'culture', 'food'],
    stayDays: 3,
    blurb:
      'A stone university city with albatross and penguin colonies on the doorstep, and a food scene built on cheese, chocolate, and the harbor.',
    tagline: 'Victorian streets, a wild peninsula, and a harbor wind that keeps the stone city honest',
    overview:
      'Dunedin is a compact stone city at the head of Otago Harbour, with a student pulse, a railway-station postcard, and a peninsula that still belongs to seabirds. January is southern summer: the warmest, busiest window for royal albatross and a long evening on the harbor, though a southerly can still feel like April in a northern city. Winter is frost, empty streets, and excellent museums. Three days is a city-and-campus day, a peninsula wildlife day, and a buffer that can become the Catlins or Moeraki if you have a car. The wildlife is the reason to come; the city is why you can eat well after a cold lookout.',
    visitorProfile:
      'For travelers who will sit in a hide for birds, walk a steep city, and treat a student town’s bars as optional rather than the point.',
    climate: 'oceanic',
    coordinates: { lat: -45.8788, lng: 170.5028 },
    airport: 'DUD — Dunedin Airport',
    timezone: 'Pacific/Auckland',
    language: 'English, te reo Māori',
    currency: 'NZD',
    walkability: 3,
    crowdLevel: 2,
    altitudeMeters: 15,
    costs: [160, 290, 580],
    gettingThere:
      'Dunedin Airport sits south of the city with a shuttle or taxi of about 30 minutes. Domestic flights from Auckland, Wellington, and Christchurch are the usual approach. The coastal road from Christchurch is a full scenic day, not a transfer.',
    gettingAround:
      'The Octagon and campus are walkable and steep. Buses are limited. A rental car is the clean way to the peninsula, Moeraki, and the Catlins. Book peninsula wildlife tours if you do not want to drive narrow roads in the wind.',
    highlights: [
      highlight('Taiaroa Head royal albatross', 'The only mainland royal albatross colony on the planet. Book the observatory; the birds do not perform on your schedule.', '2.5 hours'),
      highlight('Penguin and fur-seal coastline', 'Yellow-eyed or little penguins at dusk viewing sites, plus seals on the rocks. Stay the distance the rangers set.', '3 hours'),
      highlight('Otago Peninsula road', 'Harborside farms, a castle if you want it, and viewpoints that work even when the colony is quiet.', 'Half day'),
      highlight('Dunedin Railway Station and the Octagon', 'Stone, mosaic, and a civic square that still feels like a Scottish transplant. A short, good wander.', '90 minutes'),
      highlight('Toitū or the Otago Museum', 'Settler, Māori, and natural-history rooms that explain why the peninsula is protected. Useful in a southerly.', '2 hours'),
      highlight('Baldwin Street, then leave', 'The steep-street novelty. Walk it once if you must, then spend the hour on the harbor instead.', '30 minutes'),
    ],
    food: [
      dish('Cheese rolls', 'South Island comfort: soft cheese in a sliced roll, grilled. A bakery or home plate, not a tasting menu.'),
      dish('Otago cheese and a harbor view', 'Local wheels that make more sense here than another imported platter.'),
      dish('Bluff oysters in season', 'Southern oysters that appear in autumn and winter. Order them when the blackboard says so.'),
      dish('A chocolate or whisky stop', 'The city’s sweet and barrel trades. One of each is enough.'),
      dish('Harborside salmon or blue cod', 'Simple fish after a peninsula day. Lemon, butter, little else.'),
    ],
    nearby: [
      nearby('Otago Peninsula', 'Albatross, penguins, and Larnach if you want a house tour. The essential day.', '30–45 minutes by car'),
      nearby('Moeraki Boulders', 'Spherical concretions on a north-coast beach. Easy as a stop toward Christchurch.', '75 minutes by car'),
      nearby('The Catlins', 'Coastal forest, waterfalls, and a slower south. Better as an overnight than a rushed loop.', '2 hours by car'),
      nearby('Central Otago rail trail country', 'Inland schist and wine if you continue toward Queenstown rather than the coast.', '2 hours by car'),
    ],
    itinerary: [
      day('Stone city', 'Railway Station, Octagon, and a museum.', 'Campus and botanic garden wander.', 'A cheese-heavy dinner in town.'),
      day('Peninsula wildlife', 'Taiaroa Head at a booked hour.', 'Coastal lookouts and a late lunch.', 'Penguin dusk viewing if your tour includes it.'),
      day('Coast or buffer', 'Moeraki if you have a car and a northbound plan.', 'Otherwise a second harbor walk and coffee.', 'Airport shuttle with slack for wind.'),
    ],
    packing: [
      pack('A real windproof and a warm layer', 'January is summer and still cold on the headland. Winter needs more.'),
      pack('Binoculars', 'Albatross and penguins are not phone-zoom animals from the official distances.'),
      pack('Grippy shoes', 'Steep streets, wet grass, and farm tracks on the peninsula.'),
    ],
    tips: [
      'Book the albatross observatory before you fly. January fills; winter has fewer slots and more weather closures.',
      'Keep your distance from penguins. A close photo is a stressed bird.',
      'The city is hilly. Sleep near the Octagon if you do not want a nightly climb.',
      'Three days is enough. Add the Catlins only if you have a fourth night or a southbound car.',
    ],
    warnings: [
      'Headland wind and sudden rain close viewpoints. Do not stand on wet basalt for a better angle.',
      'Wildlife viewing after dark means farm roads and animals on the verge. Drive slowly back to town.',
    ],
    bestMonths: ['December', 'January', 'February', 'March'],
    tags: ['albatross', 'penguins', 'peninsula', 'stone-city', 'harbor'],
  },
]
